import asyncio, sys, time
from playwright.async_api import async_playwright
SK = '<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>:root{color-scheme:light;padding:env(safe-area-inset-top,0px) 0 env(safe-area-inset-bottom,0px)}body{margin:0;font:14px system-ui;background:#fafafa}img{max-width:100%}[hidden]{display:none!important}</style></head><body>'
ADV = '''(tt) => { const S = window.BBAPP; const sim = S.sim; let n = 0; if (sim.phase === 'pre') { S.countdown = 0; window.BB.startMatch(sim); }
  const humans = new Set(S.humans.map(h => h.id));
  while (sim.t < tt && n < 300*200 && sim.phase !== 'done') { if (S.step % 5 === 0) { sim.robots.forEach(r => { if (!humans.has(r.id) || sim.phase === 'auto') window.BBAI.control(sim, r, 5*window.BB.DT); }); } window.BB.advance(sim); S.step++; n++; }
  return {phase: sim.phase, t: +sim.t.toFixed(2), n}; }'''
def log(*a):
    print(*a, flush=True)
async def main():
    only = sys.argv[1] if len(sys.argv) > 1 else 'all'
    html = open('dist/biobuzz-sim.html').read()
    open('dist/_test.html','w').write(SK + html + '</body></html>')
    three = open('node_modules/three/build/three.min.js').read()
    async with async_playwright() as p:
        b = await p.chromium.launch(args=['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'])
        pg = await b.new_page(viewport={'width':1440,'height':900})
        errs = []
        pg.on('console', lambda m: errs.append(f'{m.type}: {m.text}') if m.type in ('error','warning') else None)
        pg.on('pageerror', lambda e: errs.append('PAGEERROR: ' + str(e)))
        async def route(r):
            u = r.request.url
            if 'three.min.js' in u: await r.fulfill(body=three, content_type='application/javascript')
            elif 'fonts.g' in u: await r.fulfill(body='', content_type='text/css')
            else: await r.continue_()
        await pg.route('**/*', route)
        await pg.goto('file:///home/claude/biobuzz/dist/_test.html')
        await pg.wait_for_function('document.getElementById("loading").hidden === true', timeout=90000)
        await pg.evaluate('() => { window.BBAPP.set.kbDrive = true; }')
        log('loaded'); await pg.wait_for_timeout(1500)
        await pg.screenshot(path='shots/v2_1_home.png', timeout=150000); log('shot home')
        if only in ('all', 'menus'):
            await pg.click('.nav-btn[data-screen="garage"]'); await pg.wait_for_timeout(2500)
            await pg.screenshot(path='shots/v2_2_garage.png', timeout=150000); log('shot garage')
            await pg.click('#gForm .seg[data-k="drive.type"] button[data-v="swerve"]'); await pg.wait_for_timeout(2000)
            log('garage after edit', await pg.evaluate('() => ({id: window.BBUI.g.id, name: window.BBUI.g.spec.name, drive: window.BBUI.g.spec.drive.type, customs: window.BBAPP.lib.custom.length, note: document.getElementById("gCodeOut").textContent})'))
            await pg.click('#gCopy'); await pg.wait_for_timeout(300)
            code = await pg.evaluate('() => document.getElementById("gCode").value')
            log('share code', code[:40], len(code))
            await pg.fill('#gCode', code); await pg.click('#gImport'); await pg.wait_for_timeout(800)
            log('after import', await pg.evaluate('() => ({customs: window.BBAPP.lib.custom.length, note: document.getElementById("gCodeOut").textContent})'))
            await pg.screenshot(path='shots/v2_3_garage_swerve.png', timeout=150000); log('shot garage swerve')
            await pg.click('.nav-btn[data-screen="settings"]'); await pg.wait_for_timeout(500)
            await pg.screenshot(path='shots/v2_4_settings.png', timeout=150000)
            await pg.click('#sTabs button[data-tab="keys"]'); await pg.wait_for_timeout(500)
            await pg.screenshot(path='shots/v2_5_keys.png', timeout=150000); log('shot settings')
            await pg.click('.nav-btn[data-screen="notes"]'); await pg.wait_for_timeout(400)
            await pg.screenshot(path='shots/v2_6_notes.png', timeout=150000)
            await pg.click('.nav-btn[data-screen="duo"]'); await pg.wait_for_timeout(400)
            await pg.screenshot(path='shots/v2_7_duo.png', timeout=150000); log('shot duo/notes')
            await pg.click('.nav-btn[data-screen="match"]'); await pg.wait_for_timeout(800)
            await pg.screenshot(path='shots/v2_8_match.png', timeout=150000); log('shot match setup')
        if only in ('all', 'match'):
            await pg.evaluate('() => { window.BBAPP.set.robot = "turret"; window.BBAPP.set.played = 0; }')
            await pg.evaluate('() => window.BBAPP.start("match")'); log('started match')
            await pg.wait_for_timeout(1500)
            log(await pg.evaluate(ADV, 6)); await pg.wait_for_timeout(2500)
            await pg.screenshot(path='shots/v2_9_auto.png', timeout=150000); log('shot auto')
            log(await pg.evaluate(ADV, 41))
            await pg.keyboard.down('KeyW'); await pg.wait_for_timeout(1200); await pg.keyboard.up('KeyW')
            await pg.keyboard.down('Space'); await pg.wait_for_timeout(1500); await pg.keyboard.up('Space')
            await pg.evaluate('() => { document.getElementById("banner").hidden = true; }')
            await pg.wait_for_timeout(1500)
            await pg.screenshot(path='shots/v2_10_tele.png', timeout=150000); log('shot tele')
            await pg.keyboard.press('KeyG'); await pg.wait_for_timeout(5000)
            log('aim map', await pg.evaluate('() => ({overlay: !!window.BBR.aimOverlay, pending: window.BBAPP.aim.pending, worker: !!window.BBAPP.worker})'))
            await pg.keyboard.press('Digit4'); await pg.wait_for_timeout(2500)
            await pg.screenshot(path='shots/v2_11_aimmap_top.png', timeout=150000); log('shot aim map')
            await pg.keyboard.press('KeyG'); await pg.keyboard.press('Digit2'); await pg.wait_for_timeout(1500)
            await pg.keyboard.down('Tab'); await pg.wait_for_timeout(900)
            await pg.screenshot(path='shots/v2_12_details.png', timeout=150000); await pg.keyboard.up('Tab'); log('shot details')
            await pg.keyboard.press('Digit5'); await pg.wait_for_timeout(1500)
            await pg.screenshot(path='shots/v2_13_pov.png', timeout=150000); log('shot pov')
            info = await pg.evaluate('''() => { const S = window.BBAPP; const me = S.primary(); return {phase: S.sim.phase, t: S.sim.t.toFixed(1), me: [me.x.toFixed(1), me.y.toFixed(1), (me.psi*57.3).toFixed(0)], aim: me.shooters[0].aim.reason, hop: me.hopper.length, shots: me.stats.shots, cam: S.cam}; }''')
            log(info)
            log(await pg.evaluate(ADV, 999))
            await pg.wait_for_function('document.getElementById("results").hidden === false', timeout=60000)
            await pg.wait_for_timeout(800)
            await pg.screenshot(path='shots/v2_14_results.png', timeout=150000); log('shot results')
            calls = await pg.evaluate('() => { const r = window.BBR.renderer; return {calls: r.info.render.calls, tris: r.info.render.triangles, geos: r.info.memory.geometries, tex: r.info.memory.textures}; }')
            log('render info', calls)
        if only in ('all', 'practice'):
            await pg.evaluate('() => window.BBAPP.toMenu()'); await pg.wait_for_timeout(500)
            await pg.evaluate('() => { window.BBAPP.set.pDefender = "wall"; window.BBAPP.start("practice"); }'); await pg.wait_for_timeout(1500)
            log(await pg.evaluate(ADV, 12))
            await pg.keyboard.press('Delete'); await pg.wait_for_timeout(1500)
            await pg.screenshot(path='shots/v2_15_practice.png', timeout=150000); log('shot practice')
            await pg.evaluate('() => window.BBAPP.toMenu()'); await pg.wait_for_timeout(500)
            await pg.evaluate('() => { const s = window.BBAPP.set; s.dMode = "codrive"; s.dDev1 = "kbA"; s.dDev2 = "kbB"; window.BBAPP.start("duo"); }'); await pg.wait_for_timeout(1500)
            log(await pg.evaluate(ADV, 42))
            await pg.keyboard.down('KeyW'); await pg.keyboard.down('Enter'); await pg.wait_for_timeout(1500); await pg.keyboard.up('KeyW'); await pg.keyboard.up('Enter')
            await pg.screenshot(path='shots/v2_16_codrive.png', timeout=150000); log('shot codrive')
            await pg.evaluate('() => { window.BBAPP.toMenu(); const s = window.BBAPP.set; s.dMode = "versus"; window.BBAPP.start("duo"); }'); await pg.wait_for_timeout(1500)
            log(await pg.evaluate(ADV, 42)); await pg.wait_for_timeout(1500)
            await pg.screenshot(path='shots/v2_17_versus.png', timeout=150000); log('shot versus')
        await pg.set_viewport_size({'width': 420, 'height': 860})
        await pg.evaluate('() => window.BBAPP.toMenu("match")'); await pg.wait_for_timeout(1200)
        sw = await pg.evaluate('''() => { const m = document.getElementById("menuMain"); const mr = m.getBoundingClientRect(); const wide = Array.from(m.querySelectorAll("*")).filter(e => e.offsetParent && e.getBoundingClientRect().right > mr.right + 1).slice(0, 8).map(e => e.tagName + "." + e.className + " " + Math.round(e.getBoundingClientRect().right)); return {sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth, menuSW: m.scrollWidth, menuCW: m.clientWidth, wide}; }''')
        log('narrow widths', sw)
        await pg.screenshot(path='shots/v2_18_narrow.png', timeout=150000)
        log('\n'.join(errs[:40]) or 'no console errors')
        await b.close()
asyncio.run(main())
